// Auto-generated by cbindgen - DO NOT EDIT
// geoarrow-rs C API

#ifndef GEOARROW_RS_H
#define GEOARROW_RS_H

/* Generated with cbindgen:0.29.4 */

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include <errno.h>
#ifndef ARROW_FLAG_DICTIONARY_ORDERED
#ifndef ARROW_C_DATA_INTERFACE
#define ARROW_C_DATA_INTERFACE

#define ARROW_FLAG_DICTIONARY_ORDERED 1
#define ARROW_FLAG_NULLABLE 2
#define ARROW_FLAG_MAP_KEYS_SORTED 4

struct ArrowSchema {
  const char* format;
  const char* name;
  const char* metadata;
  int64_t flags;
  int64_t n_children;
  struct ArrowSchema** children;
  struct ArrowSchema* dictionary;
  void (*release)(struct ArrowSchema*);
  void* private_data;
};

struct ArrowArray {
  int64_t length;
  int64_t null_count;
  int64_t offset;
  int64_t n_buffers;
  int64_t n_children;
  const void** buffers;
  struct ArrowArray** children;
  struct ArrowArray* dictionary;
  void (*release)(struct ArrowArray*);
  void* private_data;
};

#endif  // ARROW_C_DATA_INTERFACE

// The stream struct rides inside the outer guard, as geoarrow-c emits it: a
// later header that skips its own Arrow block on that guard (nanoarrow.h)
// still needs ArrowArrayStream defined.
#ifndef ARROW_C_STREAM_INTERFACE
#define ARROW_C_STREAM_INTERFACE

struct ArrowArrayStream {
  int (*get_schema)(struct ArrowArrayStream*, struct ArrowSchema* out);
  int (*get_next)(struct ArrowArrayStream*, struct ArrowArray* out);
  const char* (*get_last_error)(struct ArrowArrayStream*);
  void (*release)(struct ArrowArrayStream*);
  void* private_data;
};

#endif  // ARROW_C_STREAM_INTERFACE
#endif  // ARROW_FLAG_DICTIONARY_ORDERED

typedef struct ArrowSchema ArrowSchema;
typedef struct ArrowArray ArrowArray;


enum GeoArrowType
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : int32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
  GEOARROW_TYPE_UNINITIALIZED = 0,
  GEOARROW_TYPE_WKB = 100001,
  GEOARROW_TYPE_LARGE_WKB = 100002,
  GEOARROW_TYPE_WKT = 100003,
  GEOARROW_TYPE_LARGE_WKT = 100004,
  GEOARROW_TYPE_WKB_VIEW = 100005,
  GEOARROW_TYPE_WKT_VIEW = 100006,
  GEOARROW_TYPE_BOX = 990,
  GEOARROW_TYPE_BOX_Z = 1990,
  GEOARROW_TYPE_BOX_M = 2990,
  GEOARROW_TYPE_BOX_ZM = 3990,
  GEOARROW_TYPE_GEOMETRY = 991,
  GEOARROW_TYPE_INTERLEAVED_GEOMETRY = 10991,
  GEOARROW_TYPE_POINT = 1,
  GEOARROW_TYPE_LINESTRING = 2,
  GEOARROW_TYPE_POLYGON = 3,
  GEOARROW_TYPE_MULTIPOINT = 4,
  GEOARROW_TYPE_MULTILINESTRING = 5,
  GEOARROW_TYPE_MULTIPOLYGON = 6,
  GEOARROW_TYPE_GEOMETRYCOLLECTION = 7,
  GEOARROW_TYPE_POINT_Z = 1001,
  GEOARROW_TYPE_LINESTRING_Z = 1002,
  GEOARROW_TYPE_POLYGON_Z = 1003,
  GEOARROW_TYPE_MULTIPOINT_Z = 1004,
  GEOARROW_TYPE_MULTILINESTRING_Z = 1005,
  GEOARROW_TYPE_MULTIPOLYGON_Z = 1006,
  GEOARROW_TYPE_GEOMETRYCOLLECTION_Z = 1007,
  GEOARROW_TYPE_POINT_M = 2001,
  GEOARROW_TYPE_LINESTRING_M = 2002,
  GEOARROW_TYPE_POLYGON_M = 2003,
  GEOARROW_TYPE_MULTIPOINT_M = 2004,
  GEOARROW_TYPE_MULTILINESTRING_M = 2005,
  GEOARROW_TYPE_MULTIPOLYGON_M = 2006,
  GEOARROW_TYPE_GEOMETRYCOLLECTION_M = 2007,
  GEOARROW_TYPE_POINT_ZM = 3001,
  GEOARROW_TYPE_LINESTRING_ZM = 3002,
  GEOARROW_TYPE_POLYGON_ZM = 3003,
  GEOARROW_TYPE_MULTIPOINT_ZM = 3004,
  GEOARROW_TYPE_MULTILINESTRING_ZM = 3005,
  GEOARROW_TYPE_MULTIPOLYGON_ZM = 3006,
  GEOARROW_TYPE_GEOMETRYCOLLECTION_ZM = 3007,
  GEOARROW_TYPE_INTERLEAVED_POINT = 10001,
  GEOARROW_TYPE_INTERLEAVED_LINESTRING = 10002,
  GEOARROW_TYPE_INTERLEAVED_POLYGON = 10003,
  GEOARROW_TYPE_INTERLEAVED_MULTIPOINT = 10004,
  GEOARROW_TYPE_INTERLEAVED_MULTILINESTRING = 10005,
  GEOARROW_TYPE_INTERLEAVED_MULTIPOLYGON = 10006,
  GEOARROW_TYPE_INTERLEAVED_GEOMETRYCOLLECTION = 10007,
  GEOARROW_TYPE_INTERLEAVED_POINT_Z = 11001,
  GEOARROW_TYPE_INTERLEAVED_LINESTRING_Z = 11002,
  GEOARROW_TYPE_INTERLEAVED_POLYGON_Z = 11003,
  GEOARROW_TYPE_INTERLEAVED_MULTIPOINT_Z = 11004,
  GEOARROW_TYPE_INTERLEAVED_MULTILINESTRING_Z = 11005,
  GEOARROW_TYPE_INTERLEAVED_MULTIPOLYGON_Z = 11006,
  GEOARROW_TYPE_INTERLEAVED_GEOMETRYCOLLECTION_Z = 11007,
  GEOARROW_TYPE_INTERLEAVED_POINT_M = 12001,
  GEOARROW_TYPE_INTERLEAVED_LINESTRING_M = 12002,
  GEOARROW_TYPE_INTERLEAVED_POLYGON_M = 12003,
  GEOARROW_TYPE_INTERLEAVED_MULTIPOINT_M = 12004,
  GEOARROW_TYPE_INTERLEAVED_MULTILINESTRING_M = 12005,
  GEOARROW_TYPE_INTERLEAVED_MULTIPOLYGON_M = 12006,
  GEOARROW_TYPE_INTERLEAVED_GEOMETRYCOLLECTION_M = 12007,
  GEOARROW_TYPE_INTERLEAVED_POINT_ZM = 13001,
  GEOARROW_TYPE_INTERLEAVED_LINESTRING_ZM = 13002,
  GEOARROW_TYPE_INTERLEAVED_POLYGON_ZM = 13003,
  GEOARROW_TYPE_INTERLEAVED_MULTIPOINT_ZM = 13004,
  GEOARROW_TYPE_INTERLEAVED_MULTILINESTRING_ZM = 13005,
  GEOARROW_TYPE_INTERLEAVED_MULTIPOLYGON_ZM = 13006,
  GEOARROW_TYPE_INTERLEAVED_GEOMETRYCOLLECTION_ZM = 13007,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum GeoArrowType GeoArrowType;
#else
typedef int32_t GeoArrowType;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

enum GeoArrowDimensions
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : int32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
  GEOARROW_DIMENSIONS_UNKNOWN = 0,
  GEOARROW_DIMENSIONS_XY = 1,
  GEOARROW_DIMENSIONS_XYZ = 2,
  GEOARROW_DIMENSIONS_XYM = 3,
  GEOARROW_DIMENSIONS_XYZM = 4,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum GeoArrowDimensions GeoArrowDimensions;
#else
typedef int32_t GeoArrowDimensions;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

enum GeoArrowCoordType
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : int32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
  GEOARROW_COORD_TYPE_UNKNOWN = 0,
  GEOARROW_COORD_TYPE_SEPARATE = 1,
  GEOARROW_COORD_TYPE_INTERLEAVED = 2,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum GeoArrowCoordType GeoArrowCoordType;
#else
typedef int32_t GeoArrowCoordType;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

enum GeoArrowEdgeType
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : int32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
  GEOARROW_EDGE_TYPE_PLANAR = 0,
  GEOARROW_EDGE_TYPE_SPHERICAL = 1,
  GEOARROW_EDGE_TYPE_VINCENTY = 2,
  GEOARROW_EDGE_TYPE_THOMAS = 3,
  GEOARROW_EDGE_TYPE_ANDOYER = 4,
  GEOARROW_EDGE_TYPE_KARNEY = 5,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum GeoArrowEdgeType GeoArrowEdgeType;
#else
typedef int32_t GeoArrowEdgeType;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/**
 * Errno-compatible status code. [`GEOARROW_OK`] on success, otherwise one of
 * the values in `<errno.h>`.
 */
typedef int32_t GeoArrowErrorCode;

/**
 * Caller-allocated error sink. Layout-compatible with geoarrow-c's
 * `struct GeoArrowError`, so a consumer of both libraries can pass the same
 * struct to either.
 */
typedef struct GeoArrowError {
  char message[1024];
} GeoArrowError;

#define GEOARROW_OK 0

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * The library version, as a static NUL-terminated string.
 */
const char *GeoArrowRsVersion(void);

/**
 * Release an array through its embedded release callback. Null is ignored.
 *
 * # Safety
 * `array` must be null or address an array from a conforming Arrow C Data
 * Interface producer that has not already been released. The caller must not
 * use the array afterwards.
 */
void GeoArrowRsArrayRelease(ArrowArray *array);

/**
 * Release a schema through its embedded release callback. Null is ignored.
 *
 * # Safety
 * `schema` must be null or address a schema from a conforming Arrow C Data
 * Interface producer that has not already been released. The caller must not
 * use the schema afterwards.
 */
void GeoArrowRsSchemaRelease(ArrowSchema *schema);

/**
 * Write the `GeoArrowType` value describing `schema` into `out_type`. The
 * schema is borrowed, not consumed. `error` may be null. On failure nothing
 * is written to `out_type`.
 *
 * # Safety
 * `schema` must be null or address a readable [`ArrowSchema`] tree whose
 * non-null `metadata` pointers hold well-formed C Data Interface metadata
 * blocks; `out_type` must address a writable `GeoArrowType`.
 */
GeoArrowErrorCode GeoArrowRsSchemaType(const ArrowSchema *schema, GeoArrowType *out_type, struct GeoArrowError *error);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* GEOARROW_RS_H */
