//! The committed header must agree with geoarrow-c's `geoarrow_type.h`,
//! whose vocabulary it copies. A value drift would misread geometry types
//! while everything still compiles. The vocabulary checks are verbatim
//! `NAME = VALUE` searches on whitespace-normalized text: no C parsing, so a
//! reformatted geoarrow-c header fails loudly instead of parsing wrong.

use std::path::Path;

const HEADER: &str = include_str!("../geoarrow_rs.h");

const EDGE_TYPES: &[&str] = &[
    "PLANAR",
    "SPHERICAL",
    "VINCENTY",
    "THOMAS",
    "ANDOYER",
    "KARNEY",
];

fn normalize(text: &str) -> String {
    text.split_whitespace().collect::<Vec<_>>().join(" ")
}

/// True when `needle` occurs in `text` on identifier boundaries: `POINT = 1`
/// must not match inside `INTERLEAVED_POINT = 1` or `POINT = 1234`.
fn contains_entry(text: &str, needle: &str) -> bool {
    let boundary = |c: Option<char>| !c.is_some_and(|c| c.is_ascii_alphanumeric() || c == '_');
    text.match_indices(needle).any(|(i, _)| {
        boundary(text[..i].chars().next_back()) && boundary(text[i + needle.len()..].chars().next())
    })
}

fn has_pair(text: &str, name: &str, value: i64) -> bool {
    contains_entry(text, &format!("{name} = {value}"))
}

/// The vocabulary shared with geoarrow-c: names and values generated by
/// geoarrow-c's encoding,
/// `(coord_type - 1) * 10000 + (dimensions - 1) * 1000 + geometry_type`.
/// A wrong generated pair cannot pass, because it must match geoarrow-c's
/// own text below.
fn shared_vocabulary() -> Vec<(String, i64)> {
    let mut vocabulary = vec![("GEOARROW_TYPE_UNINITIALIZED".to_string(), 0)];
    let serialized = [
        "WKB",
        "LARGE_WKB",
        "WKT",
        "LARGE_WKT",
        "WKB_VIEW",
        "WKT_VIEW",
    ];
    for (i, name) in serialized.iter().enumerate() {
        vocabulary.push((format!("GEOARROW_TYPE_{name}"), 100001 + i as i64));
    }
    let dims = ["", "_Z", "_M", "_ZM"];
    for (d, dim) in dims.iter().enumerate() {
        vocabulary.push((format!("GEOARROW_TYPE_BOX{dim}"), d as i64 * 1000 + 990));
    }
    let kinds = [
        "POINT",
        "LINESTRING",
        "POLYGON",
        "MULTIPOINT",
        "MULTILINESTRING",
        "MULTIPOLYGON",
    ];
    for (c, coords) in ["", "INTERLEAVED_"].iter().enumerate() {
        for (d, dim) in dims.iter().enumerate() {
            for (g, kind) in kinds.iter().enumerate() {
                vocabulary.push((
                    format!("GEOARROW_TYPE_{coords}{kind}{dim}"),
                    c as i64 * 10000 + d as i64 * 1000 + g as i64 + 1,
                ));
            }
        }
    }
    for (i, name) in ["UNKNOWN", "XY", "XYZ", "XYM", "XYZM"].iter().enumerate() {
        vocabulary.push((format!("GEOARROW_DIMENSIONS_{name}"), i as i64));
    }
    for (i, name) in ["UNKNOWN", "SEPARATE", "INTERLEAVED"].iter().enumerate() {
        vocabulary.push((format!("GEOARROW_COORD_TYPE_{name}"), i as i64));
    }
    vocabulary
}

/// The geoarrow-c type header: from `GEOARROW_C_DIR` when set, otherwise from
/// a clone cached under `target/`. Fails loudly rather than skipping.
fn geoarrow_c_type_header() -> String {
    let header_in = |dir: &Path| dir.join("src/geoarrow/geoarrow_type.h");
    let path = if let Ok(dir) = std::env::var("GEOARROW_C_DIR") {
        header_in(Path::new(&dir))
    } else {
        let clone = Path::new(env!("CARGO_MANIFEST_DIR")).join("target/geoarrow-c");
        let header = header_in(&clone);
        if !header.exists() {
            // A leftover partial clone would make git refuse forever.
            let _ = std::fs::remove_dir_all(&clone);
            let status = std::process::Command::new("git")
                .args(["clone", "--depth", "1"])
                .arg("https://github.com/geoarrow/geoarrow-c")
                .arg(&clone)
                .status();
            assert!(
                status.map(|s| s.success()).unwrap_or(false),
                "cannot clone geoarrow-c; set GEOARROW_C_DIR to a checkout"
            );
        }
        header
    };
    std::fs::read_to_string(&path)
        .unwrap_or_else(|err| panic!("cannot read {}: {err}", path.display()))
}

#[test]
fn vocabulary_matches_geoarrow_c() {
    let ours = normalize(HEADER);
    let theirs = normalize(&geoarrow_c_type_header());

    assert!(contains_entry(&ours, "#define GEOARROW_OK 0"));
    assert!(contains_entry(&theirs, "#define GEOARROW_OK 0"));

    for (name, value) in shared_vocabulary() {
        assert!(
            has_pair(&ours, &name, value),
            "`{name} = {value}` is not in geoarrow_rs.h"
        );
        assert!(
            has_pair(&theirs, &name, value),
            "`{name} = {value}` is not in geoarrow-c"
        );
    }

    // geoarrow-c leaves GeoArrowEdgeType implicit, so those values are pinned
    // by an anchored verbatim run: the brace rules out an inserted first
    // member shifting them, and a reformat fails loudly.
    for (i, name) in EDGE_TYPES.iter().enumerate() {
        assert!(has_pair(
            &ours,
            &format!("GEOARROW_EDGE_TYPE_{name}"),
            i as i64
        ));
    }
    let edge_run = EDGE_TYPES
        .iter()
        .map(|name| format!("GEOARROW_EDGE_TYPE_{name}"))
        .collect::<Vec<_>>()
        .join(", ");
    assert!(
        theirs.contains(&format!("enum GeoArrowEdgeType {{ {edge_run} }}")),
        "geoarrow-c's GeoArrowEdgeType changed shape; re-check the values"
    );
}

/// cbindgen only emits types reachable from a signature or named in
/// cbindgen.toml's include list, so a vocabulary enum can vanish from the
/// header silently.
#[test]
fn header_declares_the_vocabulary_types() {
    for name in [
        "GeoArrowType",
        "GeoArrowDimensions",
        "GeoArrowCoordType",
        "GeoArrowEdgeType",
        "GeoArrowError",
        "GeoArrowErrorCode",
    ] {
        assert!(
            contains_entry(HEADER, name),
            "`{name}` is not in geoarrow_rs.h; add it to cbindgen.toml's include list"
        );
    }
}
